spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:testdb"
  output:
    ansi:
      enabled: always